/- ## Swap contracts: SWPPV (plain-vanilla IRS) and SWAPS (composite of legs). -/

import Actus.Contract.Engine
import Actus.Contract.Lending

namespace Actus.Contract.Execution

open Actus.Protocol
open Actus.Util
open Actus.Contract

/-- SWPPV — a plain-vanilla interest-rate swap (single contract).  Each interest
    period pays two legs: a fixed leg `IPFX = sign·N·fixedRate·Y` and a floating
    leg `IPFL = −sign·N·floatRate·Y`, where `fixedRate = nominalInterestRate`,
    `floatRate` starts at `nominalInterestRate2` and is reset by `RR` events to
    `O^rf(RRMO)·RRMLT + RRSP` (clamped).  `IED`/`MD` exchange no principal
    (payoff 0).  Gross (`D`) emits both legs; net (`S`) sums them per period. -/
def swppvCashflows (ct : Terms Float) (rf : RiskFactorEnv Float) : Cashflows :=
  let rf := { rf with yf := fun a b => yf ct a b }
  match ct.initialExchangeDate, ct.maturityDate with
  | some ied, some md =>
    let s      := Conventions.sign (α := Float) ct.contractRole
    let n      := Terms.nt ct
    let fixed  := Terms.ipnr ct
    let float0 := ct.nominalInterestRate2.getD 0
    let cfg    := ct.scheduleConfig
    let iedT   := toTime ied
    -- interest-payment dates (anchored cycle, up to & incl. maturity)
    let ipDates := (cyclicTimes cfg ct.cycleAnchorDateOfInterestPayment
                      ct.cycleOfInterestPayment ct.initialExchangeDate (some md) true).filter
                      (fun t => Nat.blt iedT t)
    -- rate-reset dates; the floating rate in force at `t` is the latest reset
    -- strictly before `t` (else the initial `nominalInterestRate2`)
    let rrDates := cyclicTimes cfg ct.cycleAnchorDateOfRateReset
                     ct.cycleOfRateReset ct.initialExchangeDate (some md) false
    let floatAt := fun (t : Time) =>
      match (rrDates.filter (fun r => Nat.blt r t)).reverse.head? with
      | some r => clampHi ct.lifeCap (clampLo ct.lifeFloor
                    (rf.marketRate r * Terms.rrmlt ct + Terms.rrsp ct))
      | none   => float0
    let bounds := iedT :: ipDates
    let flows := ((bounds.zip ipDates).map fun p =>
      let yfp := rf.yf p.1 p.2
      [((p.2, EventType.IPFX), s * n * fixed * yfp),
       ((p.2, EventType.IPFL), -s * n * floatAt p.2 * yfp)]).flatten
    -- net (cash) settlement sums the two legs of each period into one flow
    let flows := match ct.deliverySettlement with
      | some "S" =>
        (sortCF flows).foldr (fun (c : Cashflow) (acc : Cashflows) =>
          match acc with
          | a :: rest => if c.1.1 == a.1.1 then ((c.1.1, EventType.IP), c.2 + a.2) :: rest
                         else c :: acc
          | [] => [c]) ([] : Cashflows)
      | _ => flows
    -- parent termination: drop interest after the termination date, settle TD
    let flows := match ct.terminationDate with
      | some td => let tdT := toTime td + (if rf.terminationEOD then 1 else 0)
                   (flows.filter (fun c => Nat.ble c.1.1 tdT)) ++ [((tdT, EventType.TD), Terms.ptd ct)]
      | none    => flows
    -- parent purchase: drop pre-purchase flows, settle PRD
    let flows := match ct.purchaseDate with
      | some pd => let pT := toTime pd + (if rf.purchaseEOD then 1 else 0)
                   afterPurchase ct (((pT, EventType.PRD), -s * Terms.pprd ct) :: flows)
      | none    => flows
    let sdT := toTime ct.statusDate
    sortCF (flows.filter (fun c => Nat.ble sdT c.1.1))
  | _, _ => []

/-- Cash flows of a single (child) contract, dispatched on its type. -/
def legCashflows (ct : Terms Float) (rf : RiskFactorEnv Float) : Cashflows :=
  match ct.contractType with
  | .PAM => pamCashflows ct rf
  | .LAM => lamCashflows ct rf
  | .NAM => namCashflows ct rf
  | .ANN => annCashflows ct rf
  | .CLM => clmCashflows ct rf
  | _    => []

/-- SWAPS — a parent contract over two legs (`contractStructure`).  The `FIL`
    leg runs in the parent's role direction, the `SEL` leg in the opposite one;
    each leg is generated by the ordinary engine and the cash flows combined:
    gross/delivery (`deliverySettlement = D`) emits both legs' flows, while net
    (`S`) sums same-`(date, event-type)` flows.  A parent `terminationDate`
    truncates the combined flows and settles `TD`; a parent `purchaseDate` drops
    pre-purchase flows and settles `PRD` (both at the parent's clean price). -/
def swapsCashflows (ct : Terms Float) (rf : RiskFactorEnv Float) : Cashflows :=
  match ct.contractStructure with
  | some legs =>
    let s : Float := Conventions.sign (α := Float) ct.contractRole
    let parentPos : Bool := s > 0
    let legCf : ContractStructure Float → Cashflows
      | .mk (.referenceTerms child) role _ =>
        let pos := match role with
          | .SEL => !parentPos
          | _    => parentPos            -- FIL (and default): parent direction
        -- each leg resolves its own rate-reset series by market-object code
        let legRf := { rf with marketRate :=
          match child.marketObjectCodeOfRateReset with
          | some m => rf.marketRateOf m
          | none   => rf.marketRate }
        legCashflows { child with contractRole := if pos then .CR_RPA else .CR_RPL } legRf
      | .mk (.referenceId _) _ _ => []
    let sorted := sortCF (legs.map legCf).flatten
    -- net (cash) settlement sums same-(date, event-type) leg flows into one;
    -- gross (delivery) keeps both legs' flows
    let combined := match ct.deliverySettlement with
      | some "S" =>
        sorted.foldr (fun (c : Cashflow) acc =>
          match acc with
          | a :: rest =>
            if c.1.1 == a.1.1 && eventTypePriority c.1.2 == eventTypePriority a.1.2
            then (c.1, c.2 + a.2) :: rest else c :: acc
          | [] => [c]) []
      | _ => sorted
    -- parent termination: drop flows after the termination date, settle `TD`
    let combined := match ct.terminationDate with
      | some td => let tdT := toTime td
                   (combined.filter (fun c => Nat.ble c.1.1 tdT)) ++ [((tdT, EventType.TD), s * Terms.ptd ct)]
      | none    => combined
    -- parent purchase: drop pre-purchase flows, settle `PRD` at the clean price
    let combined := match ct.purchaseDate with
      | some pd =>
        let pT := toTime pd + (if rf.purchaseEOD then 1 else 0)   -- 23:59:59 settles next midnight
        afterPurchase ct (((pT, EventType.PRD), s * Terms.pprd ct) :: combined)
      | none    => combined
    sortCF combined
  | none => []

end Actus.Contract.Execution
